
import { jsPDF } from 'jspdf';
import type { AnalyzePancreasScanOutput } from '@/ai/flows/analyze-pancreas-scan';
import { format } from 'date-fns';

// Helper function to add text and auto-wrap if necessary
const addWrappedText = (
  doc: jsPDF,
  text: string | string[],
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number,
  options?: any
): number => {
  const lines = doc.splitTextToSize(text, maxWidth);
  doc.text(lines, x, y, options);
  return y + lines.length * lineHeight;
};


export function generateReportPDF(analysisResult: AnalyzePancreasScanOutput, mostLikelyCondition: { name: string, probability: number } | null) {
  const doc = new jsPDF();
  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;
  const margin = 15;
  let currentY = margin;

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Pancreas Vision - AI Analysis Report', pageWidth / 2, currentY, { align: 'center' });
  currentY += 10;

  // Date
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date: ${format(new Date(), 'MMMM dd, yyyy')}`, margin, currentY);
  currentY += 10;

  // Separator
  doc.setDrawColor(180, 180, 180); // Light gray
  doc.line(margin, currentY, pageWidth - margin, currentY);
  currentY += 10;

  // Analysis Results Section
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Analysis Results:', margin, currentY);
  currentY += 8;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  const diseaseDisplayNameMap: Record<keyof AnalyzePancreasScanOutput, string> = {
    pancreaticCancerProbability: 'Pancreatic Cancer',
    chronicPancreatitisProbability: 'Chronic Pancreatitis',
    pancreaticCystsProbability: 'Pancreatic Cysts',
    acutePancreatitisProbability: 'Acute Pancreatitis',
  };

  for (const [key, probability] of Object.entries(analysisResult)) {
    const displayName = diseaseDisplayNameMap[key as keyof AnalyzePancreasScanOutput] || key;
    const text = `${displayName}: ${(Number(probability) * 100).toFixed(1)}% probability`;
    if (currentY + 6 > pageHeight - margin) { // Check for page break
      doc.addPage();
      currentY = margin;
    }
    doc.text(text, margin + 5, currentY);
    currentY += 7;
  }
  currentY += 5;

  // Separator
  doc.line(margin, currentY, pageWidth - margin, currentY);
  currentY += 10;

  // Important Note(s) Section
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Important Notes:', margin, currentY);
  currentY += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const lineHeight = 5;
  const textMaxWidth = pageWidth - margin * 2;

  // Specific warning if applicable
  if (mostLikelyCondition && mostLikelyCondition.probability > 50) {
    const warningText = `The analysis indicates a notable probability for ${mostLikelyCondition.name}. This tool provides preliminary insights and is not a substitute for professional medical diagnosis. Please consult a qualified healthcare professional for further evaluation and advice.`;
    currentY = addWrappedText(doc, warningText, margin, currentY, textMaxWidth, lineHeight, { CPY: currentY });
    currentY += 5; // Extra space after warning
  }

  // General Disclaimer
  const disclaimerText = 'Disclaimer: These results are generated by an AI model and should be used for informational purposes only. This report and the AI analysis do not constitute medical advice, diagnosis, or treatment. Always consult with a qualified medical professional for any health concerns or before making any decisions related to your health or treatment.';
  currentY = addWrappedText(doc, disclaimerText, margin, currentY, textMaxWidth, lineHeight, { CPY: currentY });
  currentY += 10;
  
  // Footer with page number (simple version)
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Page ${i} of ${pageCount} | Pancreas Vision Report`,
      pageWidth / 2,
      pageHeight - margin / 2,
      { align: 'center' }
    );
  }

  doc.save('PancreasVision_Report.pdf');
}
